### your site title here

title: Sarah H.Q. Li
description: Assistant Professor, Georgia Tech Aerospace Engineering | sarahli@gatech [dot] edu

baseurl: ""
url: #custom url to be used instead of GitHub repository
email: sarahli@gatech.edu


highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->

# Pagination
paginate: 5
# permalink: /blog/:year/:title/
paginate_path: /page:num/

# google scholar

scholar:
  order: ascending
  bibliography_template: bib
  repository: publications

# Social media links in footer
#facebook: "#"
# twitter: varchanaiyer_
linkedin: lisarah1
github: lisarah
researchgate: Sarah-Li-25
orcid: 0000-0001-5265-8929

highlighter: rouge
markdown: kramdown

# Tracker
analytics:
google_analytics: U G-FRXS9P3W29

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-scholar
  # - jekyll-scholar-extras
